apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-network-policies
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/nutjomjom/test-netpol.git
        revision: test
        directories:
          - path: test/overlay/*/*
  template:
    metadata:
      name: "{{path.dirpath.basename}}-{{path.basename}}-network-policy"
    spec:
      project: default
      source:
        repoURL: https://github.com/nutjomjom/test-netpol.git
        targetRevision: test
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{path.basename}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
